return {
  ["desc"]="由脚本dstserver.sh创建！",
  ["hideminimap"]=false,
  id="SURVIVAL_TOGETHER",
  ["location"]="forest",
  ["max_playlist_position"]=999,
  ["min_playlist_position"]=0,
  ["name"]="游山玩水--由脚本dstserver.sh创建！",
  ["numrandom_set_pieces"]=4,
  ["override_level_string"]=false,
  overrides={
    ["has_ocean"]=true,
  ["no_joining_islands"]=true,
    ["no_wormholes_to_disconnected_tiles"]=true,
    ["keep_disconnected_tiles"]=true,
