},
  ["random_set_pieces"]={
    "Sculptures_2",
    "Sculptures_3",
    "Sculptures_4",
    "Sculptures_5",
    "Chessy_1",
    "Chessy_2",
    "Chessy_3",
    "Chessy_4",
    "Chessy_5",
    "Chessy_6",
    "Maxwell1",
    "Maxwell2",
    "Maxwell3",
    "Maxwell4",
    "Maxwell6",
    "Maxwell7",
    "Warzone_1",
    "Warzone_2",
    "Warzone_3"
  },
  ["required_prefabs"]={ "multiplayer_portal" },
  ["required_setpieces"]={ "Sculptures_1", "Maxwell5" },
  ["substitutes"]={},
  ["version"]=4
}
