return {
    background_node_range={ 0, 1 },
    desc="由脚本dstserver.sh创建！",
    hideminimap=false,
    id="LAVAARENA",
    location="lavaarena",
    max_playlist_position=999,
    min_playlist_position=0,
    name="熔炉斗兽场--由脚本dstserver.sh创建！",
    numrandom_set_pieces=0,
    override_level_string=false,
    overrides={
      has_ocean=false,
      boons="never",
      keep_disconnected_tiles=true,
      layout_mode="RestrictNodesByKey",
      poi="never",
      protected="never",
      roads="never",
      season_start="default",
      start_location="lavaarena",
      task_set="lavaarena_taskset",
      touchstone="never",
      traps="never",
      world_size="small"
    },
    required_prefabs={ "lavaarena_portal" },
    substitutes={  },
    version=4
  }
