return {
  background_node_range={ 0, 0 },
  desc="你能经受暴食的挑战吗？--由脚本dstserver.sh创建！",
  hideminimap=false,
  id="QUAGMIRE",
  location="quagmire",
  max_playlist_position=999,
  min_playlist_position=0,
  name="暴食：你会做饭吗？--由脚本dstserver.sh创建！",
  numrandom_set_pieces=0,
  override_level_string=false,
  overrides={
    boons="never",
    branching="random",
    disease_delay="none",
    keep_disconnected_tiles=false,
    layout_mode="RestrictNodesByKey",
    loop_percent=0,
    no_joining_islands=true,
    no_wormholes_to_disconnected_tiles=true,
    petrification="none",
    poi="never",
    prefabswaps_start="classic",
    protected="never",
    roads="never",
    season_start="default",
    start_location="quagmire_startlocation",
    task_set="quagmire_taskset",
    touchstone="never",
    traps="never",
    wildfires="never",
    world_size="small"
  },
  required_prefabs={ "quagmire_portal" },
  substitutes={  },
  version=4
}
